### ISSUE TITLE
can you give a json that i can use you plugins

### ISSUE THREAD

**Issue by Rigaln** [joshua-software-dev/SizeMattersFishing#1]
can you give a json that i can use you plugins

**Comment by joshua-software-dev** [comment]
Sorry, I probably won't be self hosting this. This plugin is presently pending review to get accepted to official plugin list, and will be available from the plugin testing builds soon.

In the meantime, if you're willing to install by unzipping files into your dalamud install directory, the precompiled releases are here. https://github.com/joshua-software-dev/SizeMattersFishing/releases/tag/latest

Hopefully the approval shouldn't take too much longer, sorry for the inconvenience.

**Comment by joshua-software-dev** [comment]
![testing](https://user-images.githubusercontent.com/55586380/153690124-510cda28-f1d1-43c9-ba1c-0003661db997.png)

This is now available with the "plugin testing builds" setting enabled in the in-game plugin installer. Please test it out and let me know if there are any issues I did not encounter while developing it. If all goes well, it should get moved from testing to standard plugins shortly thereafter.

**Comment by Rigaln** [comment]
Thank you.
